name: fitness_prodigy
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0
  fluttertoast: ^8.2.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  meta: ^1.9.1
  intl: ^0.18.1
  flutter_animate: ^4.2.0+1
  keyboard_dismisser: ^3.0.0
  dio: ^5.3.3
  lottie: ^2.6.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  retrofit: ^4.0.3
  get_it: ^7.6.4
  injectable: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  retrofit_generator: ^8.0.2
  injectable_generator: ^2.4.1
  mocktail: ^1.0.1
  bloc_test: ^9.1.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/fp2.png"




flutter:

 
  uses-material-design: true
  generate: true

  
  assets:
    - images/
    - exercise_examples_page_images/
    - images_supplements/
    - images_diet/
    - assets_weather/




