// List quotes = [
//   " ''Strength doesn't come from what you can do; it comes from overcoming the things you once thought you couldn't.'' - Rikki Rogers",
//   " ''Success is walking from failure to failure with no loss of enthusiasm.'' - Winston Churchill",
//   " ''The only bad workout is the one that didn't happen.'' - Unknown",
//   " ''Your body can stand almost anything; it's your mind you have to convince.'' - Unknown",
//   " ''The harder the battle, the sweeter the victory.'' - Les Brown",
//   " ''Don't count the days; make the days count.'' - Muhammad Ali",
//   " ''Sweat is just fat crying.'' - Unknown",
//   " ''The only person you should try to be better than is the person you were yesterday.'' - Unknown",
//   " ''It's not about having time; it's about making time.'' - Unknown",
//   " ''Believe in yourself, and you will be unstoppable.'' - Unknown",
//   " ''Strength grows in the moments when you think you can't go on but keep going anyway.'' - Unknown",
//   " ''Success is a journey, not a destination.'' - Arthur Ashe",
//   " ''The pain you feel today will be the strength you feel tomorrow.'' - Unknown",
//   " ''Excuses don't burn calories.'' - Unknown",
//   " ''Fitness is not about being better than someone else; it's about being better than you used to be.'' - Unknown",
//   " ''The body achieves what the mind believes.'' - Napoleon Hill",
//   " ''The difference between a goal and a dream is a deadline.'' - Steve Smith",
//   " ''Make your vision so clear that your fears become irrelevant.'' - Unknown",
//   " ''Winners never quit, and quitters never win.'' - Vince Lombardi",
//   " ''Every workout is a step closer to your goals.'' - Unknown",
//   " ''You are only limited by your imagination'' - Unknown",
//   " ''Champions aren't built on the days they feel motivated but the days they feel like quitting'' - Unknown",
//   """ ''No carelessness in my action,
// No confusion in my words,
// No imprecision in my thoughts.'' - Unknown""",
//   " ''There is nothing impossible to him who will try'' - Alexander the Great",
//   " ''I am not afraid of an army of lions led by a sheep; I am afraid of an army of sheep led by a lion.'' - Alexander the Great",
//   " ''I would rather live a short life of glory than a long one of obscurity.'' - Alexander the Great",
//   " ''There is nothing impossible to him who will try.'' - Alexander the Great",
//   " ''We all love ourselves more than other people, but care more about thier opinion than our own.'' - Marcus Aurelius",
//   " ''It's not what happens to you but how you react to it that matters '' - Epictetus",
//   " ''Have patience, all things are difficult before they become easy '' - Saadi",
//   " ''Do not expect life to be fair '' - Unknown",
//   " ''It is a shame for a man to grow old without seeing the beauty and strength which his body is capable '' - Socrates",
//   """ ''We live in the present,
// We dream of the future,
// And we learn eternal truths from the past., '' - Madame Chiang Kai-Shek"""
//       " ''Wolves do not lose sleep over the opinions of sheep '' - Unknown",
//   " ''I may not be there yet, but I'm closer than I was yesterday '' - Unknown",
//   " ''Once you see results, it becomes an addiction. '' - Unknown",
//   " ''The moment of pain is worth a lifetime of glory '' - Unknown",
//   " ''The pain you feel today will be the strength you feel tomorrow '' - Unknown",
//   " ''The happiness of your life depends upon the quality of your thoughts '' - Marcus Aurelius",
//   " ''I count him braver who overcomes his desires than him who conquers his enemies, for the hardest victory is over self '' - Aristotle",
//   " ''Everything you can imagine is real '' - Pablo Picasso",
//   " ''Isn't it time to embrace change and become the person you've always wanted to be? '' - Unknown",
//   " ''Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. '' - Albert Schweitzer",
//   " ''The only limit to our realization of tomorrow will be our doubts of today. '' - Franklin D. Roosevelt",
//   " ''Don't watch the clock; do what it does. Keep going. '' - Sam Levenson",
//   " ''You don't have to be great to start, but you have to start to be great. '' - Zig Ziglar",
//   " ''The only way to do great work is to love what you do. '' - Steve Jobs",
//   " ''Success is walking from failure to failure with no loss of enthusiasm. '' - Winston Churchill",
//   " ''Dream big and dare to fail. '' - Norman Vaughan",
//   " ''The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. '' - Vince Lombardi",
//   " ''Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.'' - Christian D. Larson",
//   " ''Your body is a reflection of your lifestyle.'' - Unknown",
//   " ''Every accomplishment starts with the decision to try.'' - Unknown",
//   " ''The only person you are destined to become is the person you decide to be.'' - Ralph Waldo Emerson",
//   " ''Strength doesn't come from what you can do. It comes from overcoming the things you once thought you couldn't. '' - Rikki Rogers",
//   " ''The greatest glory in living lies not in never falling, but in rising every time we fall. '' - Nelson Mandela",
//   " ''The road to success and the road to failure are almost exactly the same. '' - Colin R. Davis",
//   " ''Success is not final, failure is not fatal: It is the courage to continue that counts. '' - Winston Churchill",
//   " ''You are stronger than you think.'' - Unknown",
//   " ''Be the energy you want to attract.'' - Unknown",
//   " ''The only bad workout is the one that didn't happen.'' - Unknown",
//   " ''You are what you repeatedly do. Excellence is not an act, but a habit. '' - Aristotle",
// ];
