// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaO0VpV9CVp8ShM_rAxXWjLwjotkCTU8w',
    appId: '1:1069765458708:web:d2729d0360163b22596001',
    messagingSenderId: '1069765458708',
    projectId: 'fitness-prodigy-94',
    authDomain: 'fitness-prodigy-94.firebaseapp.com',
    storageBucket: 'fitness-prodigy-94.appspot.com',
    measurementId: 'G-DP6M1R5KJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLUEILG8kNISRJXseqyk7l9pgkU6TsnBM',
    appId: '1:1069765458708:android:f979e477f1c74e46596001',
    messagingSenderId: '1069765458708',
    projectId: 'fitness-prodigy-94',
    storageBucket: 'fitness-prodigy-94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm8fAyGGSnUtyI5RJzcPr_v6UEN5DsKCA',
    appId: '1:1069765458708:ios:c966798d4cc6217f596001',
    messagingSenderId: '1069765458708',
    projectId: 'fitness-prodigy-94',
    storageBucket: 'fitness-prodigy-94.appspot.com',
    iosBundleId: 'com.mateuszkasprzak.fitnessProdigy',
  );
}
